using Content.Client.UserInterface.Controls;
using Content.Shared._Impstation.CCVar;
using Content.Shared._Impstation.Notifier;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.Notifier.UI;

[GenerateTypedNameReferences]
public sealed partial class NotifierWindow : FancyWindow
{
    [Dependency] private readonly IClientNotifierManager _notifierManager = default!;
    [Dependency] private readonly IConfigurationManager _configManager = default!;
    [Dependency] private readonly ISharedPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    private string? SavedChangesText;
    private string? UnsavedChangesText;

    public NotifierWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        //Init the save button.
        SaveNotifierSettings.OnPressed += _ =>
        {
            SaveNotifierSettings.Disabled = true;
            _notifierManager.UpdateNotifier(GetSettings());
        };

        //make it so we run UpdateUi when we receive data from the ui.
        _notifierManager.OnServerDataLoaded += UpdateUi;
        if (_notifierManager.HasLoaded)
            UpdateUi();

        //Text input setup
        var maxLength =  _configManager.GetCVar(ImpCCVars.NotifierFreetextMaxLength);
        var length = Rope.Collapse(NotifierFreetext.TextRope).Length;
        CharacterLimit.Text = Loc.GetString("notifier-window-char-limit", ("length", length), ("maxLength", maxLength));

        NotifierFreetext.Placeholder = new Rope.Leaf(Loc.GetString("notifier-window-freetext-placeholder"));
        NotifierFreetext.OnTextChanged += _ => UnsavedChanges();
        EnableNotifierCheckBox.OnToggled += _ => UnsavedChanges();
    }

    protected override void Dispose(bool disposing)
    {
        // get rid of the window
        base.Dispose(disposing);
        // make it so we ignore the server
        if (disposing)
            _notifierManager.OnServerDataLoaded -= UpdateUi;
    }

    /// <summary>
    /// Get the players current settings.
    /// </summary>
    /// <returns></returns>
    private PlayerNotifierSettings GetSettings()
    {
        var text = Rope.Collapse(NotifierFreetext.TextRope);
        var toggled = EnableNotifierCheckBox.Pressed;

        return new(text, toggled);
    }

    /// <summary>
    /// Checks if there are changes, and if valid tell the user to save.
    /// </summary>
    private void UnsavedChanges()
    {
        // Validate freetext length
        var maxLength =  _configManager.GetCVar(ImpCCVars.NotifierFreetextMaxLength);
        var length = Rope.Collapse(NotifierFreetext.TextRope).Length;

        // if invalid warn user and return.
        if (length > maxLength)
        {
            SaveNotifierSettings.Disabled = true;
            CharacterLimit.Text = Loc.GetString("notifier-window-exceeded-char-limit", ("length", length), ("maxLength", maxLength));
            CharacterLimit.FontColorOverride = Color.Red;

            return;
        }


        // If everything is valid, enable save button and inform user they need to save.
        CharacterLimit.Text = Loc.GetString("notifier-window-char-limit", ("length", length), ("maxLength", maxLength));
        UnsavedChangesWarning.Text = UnsavedChangesText;
        UnsavedChangesWarning.FontColorOverride = Color.Red;
        SaveNotifierSettings.Disabled = false;
    }

    /// <summary>
    /// Update the ui to most current information.
    /// </summary>
    public void UpdateUi()
    {
        var notifier = _notifierManager.GetNotifier();

        if (UnsavedChangesText == null && SavedChangesText == null)
        {
            SavedChangesText = Loc.GetString("notifier-window-saved-changes");
            UnsavedChangesText = Loc.GetString("notifier-window-unsaved-changes");
        }

        NotifierFreetext.TextRope = new Rope.Leaf(notifier.Freetext);
        EnableNotifierCheckBox.Pressed = notifier.Enabled;


        CharacterLimit.FontColorOverride = null;
        SaveNotifierSettings.Disabled = true;
        UnsavedChangesWarning.Text = SavedChangesText;
        UnsavedChangesWarning.FontColorOverride = null;
    }
}
