- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/_Impstation/meta.yml
  minPlayers: 35
  maxPlayers: 80
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Meta Station {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs: # Total of 72 jobs roundstart, max of 92 inc. latejoins and trainees. she's normal now.
            # command - 9
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            AdministrativeAssistant: [ 1, 1 ] # imp
            ChiefEngineer: [ 1, 1 ]
            ChiefMedicalOfficer: [ 1, 1 ]
            ResearchDirector: [ 1, 1 ]
            HeadOfSecurity: [ 1, 1 ]
            HospitalityDirector: [ 1, 1 ] # imp
            Quartermaster: [ 1, 1 ]
            # service - 17 incl. service worker
            Bartender: [ 2, 2 ]
            Botanist: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Chef: [ 2, 2 ]
            Clown: [ 1, 1 ]
            Janitor: [ 2, 2 ]
            Librarian: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            Reporter: [ 2, 2 ]
            #ServiceWorker: [ 2, 2 ] #imp
            # engineering - 9-15
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 6, 6 ]
            TechnicalAssistant: [ 6, 6 ]
            # medical - 8-12
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 4, 4 ]
            MedicalIntern: [ 4, 4 ]
            Paramedic: [ 2, 2 ]
            # science - 10-13
            Borg: [ 4, 4 ] # yeah fuck it why not
            ResearchAssistant: [ 3, 3 ]
            Scientist: [ 5, 5 ]
            StationAi: [ 1, 1 ]
            # security - 11-15
            Brigmedic: [ 1, 1 ] # imp
            Detective: [ 1, 1 ]
            Lawyer: [ 2, 2 ]
            SecurityCadet: [ 4, 4 ]
            SecurityOfficer: [ 6, 6 ]
            Warden: [ 1, 1 ]
            # supply - 8-11
            CargoTechnician: [ 4, 4 ]
            Courier: [ 1, 1 ] # imp
            SalvageSpecialist: [ 3, 3 ]
            SupplyAssistant: [ 3, 3 ] # imp
            # civilian
            Passenger: [ -1, -1 ]
