- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hrs, imp
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    neck: ClothingNeckNoviceMark # imp
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket1: TutorialPersonalAI #imp
    pocket2: BookMedicalReferenceBook
  # storage:
  #   back:
  #   - Stuff
