using Content.Client.UserInterface.Controls;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Goobstation.Heretic.UI;


[GenerateTypedNameReferences]
public sealed partial class GhoulNotifMenu : FancyWindow
{
    public GhoulNotifMenu()
    {
        RobustXamlLoader.Load(this);

        GhoulNotif.SetMarkup(Loc.GetString("ghoul-notif-text"));

        ConfirmButton.OnPressed += _ => Close();
    }
}
