using Content.Client.UserInterface.Controls;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Goobstation.Heretic.UI;


[GenerateTypedNameReferences]
public sealed partial class HellMemoryMenu : FancyWindow
{
    public HellMemoryMenu()
    {
        RobustXamlLoader.Load(this);

        MemoryNotif.SetMarkup(Loc.GetString("hell-memory-text"));

        ConfirmButton.OnPressed += _ => Close();
    }
}
