using Content.Client._DV.CartridgeLoader.Cartridges;
using Content.Shared._Impstation.NanoChat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Impstation.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class AdminNanoChatMessageEntry : BoxContainer
{
    public AdminNanoChatMessageEntry(AdminNanoChatLogEntry log)
    {
        RobustXamlLoader.Load(this);

        SenderLabel.Text = "Sent from " + log.Sender;
        SenderLabel.Modulate = NanoChatMessageBubble.TextColor;

        CardLabel.Text = log.Card + " at " + log.Timestamp.ToString();
        CardLabel.Modulate = NanoChatMessageBubble.TextColor;

        MessageText.Text = log.Message;
        MessageText.Modulate = NanoChatMessageBubble.TextColor;

        RecipientsLabel.Text = "Sent to " + log.Recipients;
        RecipientsLabel.Modulate = NanoChatMessageBubble.TextColor;

        if (MessagePanel.PanelOverride is not StyleBoxFlat)
            return;

        var style = (StyleBoxFlat)MessagePanel.PanelOverride;
        style.BackgroundColor = NanoChatMessageBubble.OtherMessageColor;
        style.BorderColor = NanoChatMessageBubble.BorderColor;
    }
}
