using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Impstation.NanoChat;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._Impstation.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class AdminNanoChatLogsWindow : DefaultWindow
{
    public Action? OnRefresh;
    private PlayerInfo? _currentPlayer;

    public AdminNanoChatLogsWindow()
    {
        RobustXamlLoader.Load(this);

        PopulatePlayers();

        PlayerSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            PlayerSelector.PlayerListContainer.DirtyList();
            OnRefresh?.Invoke();
        };

        Refresh.OnPressed += _ =>
        {
            OnRefresh?.Invoke();
        };
    }

    public void SelectPlayer(NetUserId player)
    {
        if (!PlayerSelector.PlayerInfo.TryFirstOrDefault(
            i => i.SessionId == player, out var info))
        {
            return;
        }

        PlayerSelector.PopulateList();
        PlayerSelector.PlayerListContainer.Select(new PlayerListData(info));
    }

    public void PopulatePlayers()
    {
        PlayerSelector.PopulateList();
    }

    public void PopulateLogs(List<AdminNanoChatLogEntry> logs)
    {
        MessageArea.DisposeAllChildren();

        if (_currentPlayer is null)
            return;

        foreach (var log in logs)
        {
            if (_currentPlayer.SessionId != log.SenderUser)
                continue;
            MessageArea.AddChild(new AdminNanoChatMessageEntry(log));
        }
    }
}
