# Static

- type: latheRecipePack
  id: ImpLightPack
  recipes:
    - UvLightTube
    - LightReplacer

- type: latheRecipePack
  id: ImpServiceStatic
  recipes:
    - Mousetrap
    - TrashBag
    - DeskBell
    - PrizeTicketGold
    - PrizeTicketSilver
    - PrizeTicketBronze

- type: latheRecipePack
  id: CleanPack
  recipes:
    - Plunger
    - MopBucket
    - SoapNT
    - WelderJanitorial

- type: latheRecipePack
  id: BotanyPack
  recipes:
    - DiseaseSwab
    - HydroponicsToolMiniHoe
    - HydroponicsToolScythe
    - HydroponicsToolHatchet
    - HydroponicsToolSpade
    - HydroponicsToolClippers
    - Shovel
    - PlantBag

- type: latheRecipePack
  id: BarPack
  recipes:
    - DrinkShaker
    - DrinkJigger
    - DrinkFlaskBar
    - DrinkVacuumFlask
    - DrinkVacuumFlaskXL
    - DrinkTeapotEmpty
    - DrinkTeacupEmpty
    - DrinkWaterBottleEmpty
    - Pitcher
    - BarSpoon
    - DrinkDisposableCup
    - DrinkNoveltyMug

- type: latheRecipePack
  id: KitchenPack
  recipes:
    - KitchenKnife
    - RollingPin
    - Fork
    - Spoon
    - ForkPlastic
    - SpoonPlastic
    - PairedChopsticks

- type: latheRecipePack
  id: ServiceMiscPack
  recipes:
    - Dropper
    - ClothingHeadHatCone
    - SprayPainter
    - FlashlightLantern
    - ClothingBeltPlushie

- type: latheRecipePack
  id: LunchboxPack
  recipes:
    - SteelLunchbox
    - SteelLunchboxBlue
    - SteelLunchboxPink
    - SteelLunchboxOrange

# Dynamic

- type: latheRecipePack
  id: CleanPackDynamic
  recipes:
    - MegaSprayBottle
    - AdvMopItem
    - WeaponSprayNozzle
    - ClothingBackpackWaterTank
    - CleanerGrenade

#- type: latheRecipePack # disabled until there is something to fish
#  id: ServiceMiscPackDynamic
#  recipes:
#    - FishingRod

# Emagged

- type: latheRecipePack
  id: ServiceEmagged
  recipes:
    - ButchCleaver
    - PrizeTicketDiamond
