- type: entity
  id: MiniGyroscopeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: mini gyroscope machine board
  components:
  - type: MachineBoard
    prototype: MiniGyroscope
    stackRequirements:
      Manipulator: 2
      Glass: 2

- type: entity
  id: ServiceTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: service techfab machine board
  description: A machine printed circuit board for a Service techfab.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ServiceTechFab
      stackRequirements:
        Manipulator: 4
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker
    - type: StealTarget
      stealGroup: ServiceTechFab

- type: entity
  id: ImpCoffeeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: spacepresso machine board
  description: A machine printed circuit board for a spacepresso machine.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: ImpCoffeeMachineEmpty
      stackRequirements:
        Steel: 5
      tagRequirements:
          GlassBeaker:
            amount: 1
            defaultPrototype: Beaker

- type: entity
  id: PrizeCounterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: prize counter machine board
  description: A machine printed circuit board for a prize counter.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: PrizeCounter
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  parent: BaseMachineCircuitboard
  id: PortableCutterMachineCircuitboard
  name: portable cutter machine board
  description: A machine printed circuit board for a portable cutter machine.
  categories: [ DoNotMap ] #you only get one
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: PortableCutterMachine
    stackRequirements:
      Steel: 2
      Manipulator: 2
      Cable: 1
  - type: StealTarget
    stealGroup: HDCutterMachine

- type: entity
  id: PrinterDocSyndicateMachineCircuitboard
  parent: [ BaseMachineCircuitboard, BaseSyndicateContraband ]
  name: Syndicate document printer machine board
  description: A machine printed circuit board for a Syndicate document printer
  components:
    - type: MachineBoard
      prototype: PrinterDocSyndicate
      stackRequirements:
        Manipulator: 1
        Glass: 1
