using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Impstation.Heretic.Store;

/// <summary>
/// Control for individual listings in the heretic store.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HereticStoreListingControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ListingDataWithCostModifiers _data;

    private readonly bool _hasBalance;
    private readonly string _price;
    private readonly string? _power;

    public HereticStoreListingControl(ListingDataWithCostModifiers data, string price, bool hasBalance, Texture? texture = null, string? power = null)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _data = data;
        _hasBalance = hasBalance;
        _price = price;
        _power = power;

        StoreItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);
        StoreItemDescription.SetMessage(ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(_data, _prototype));
        StoreItemFlavor.SetMessage(ListingLocalisationHelpers.GetLocalisedFlavorText(_data));

        UpdateBuyButtonText();
        StoreItemBuyButton.Disabled = !CanBuy();

        StoreItemTexture.Texture = texture;
    }

    /// <summary>
    /// Is the listing buyable or not (either due to a lack of points or lack of power).
    /// </summary>
    private bool CanBuy()
    {
        if (!_data.Buyable)
            return false;

        if (!_hasBalance)
            return false;

        return true;
    }

    /// <summary>
    /// Updates the buy button text with FrameUpdate.
    /// </summary>
    private void UpdateBuyButtonText()
    {
        if (!_data.Buyable)
        {
            StoreItemBuyButton.Text = "Unavailable";
        }
        else
        {
            StoreItemBuyButton.Text = _price;
        }

        if (_power != null)
        {
            PowerSubText.Text = _power;
        }
    }

    /// <summary>
    /// Updates the listing name with FrameUpdate.
    /// </summary>
    private void UpdateName()
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(_data, _prototype);

        StoreItemName.Text = name;
    }

    /// <summary>
    /// Updates listing's name and description every frame.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateBuyButtonText();
        UpdateName();
        StoreItemBuyButton.Disabled = !CanBuy();
    }
}
