using System.Linq;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Heretic.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Impstation.Heretic.Store;

/// <summary>
/// Menu for the heretic store.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HereticMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;

    public Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;
    private List<ListingDataWithCostModifiers> _cachedListings = new();

    public HereticMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);
    }

    /// <summary>
    /// Update the balance.
    /// </summary>
    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        Balance = balance;

        var currency = balance.ToDictionary(type =>
            (type.Key, type.Value), type => _prototypeManager.Index(type.Key));

        var balanceStr = string.Empty;
        foreach (var ((_, amount), proto) in currency)
        {
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(proto.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup(balanceStr.TrimEnd());
    }

    /// <summary>
    /// Update our listings.
    /// </summary>
    public void UpdateListing(List<ListingDataWithCostModifiers> listings)
    {
        _cachedListings = listings;

        UpdateListing();
    }

    /// <summary>
    /// Get our listings and add them to the listing container. Used with the UpdateListing(List<ListingDataWithCostModifiers> listings).
    /// </summary>
    public void UpdateListing()
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority)
                                    .ThenBy(l => l.Cost.Values.Sum());

        // should probably chunk these out instead. to-do if this clogs the internet tubes.
        // maybe read clients prototypes instead?
        ClearListings();
        foreach (var item in sorted)
        {
            AddListingGui(item);
        }
    }

    /// <summary>
    /// Get listing data, make a control for it, and add it to the listing container. Used with UpdateListing().
    /// </summary>
    private void AddListingGui(ListingDataWithCostModifiers listing)
    {
        if (!listing.Categories.Contains(CurrentCategory))
            return;

        var hasBalance = listing.CanBuyWith(Balance);

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            if (texture == null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_entityManager.System<ActionsSystem>().GetAction(actionId)?.Comp?.Icon is { } icon)
                texture = spriteSys.Frame0(icon);
        }
        string? extraText = GetExtraText(listing);

        var listingInStock = GetListingPriceString(listing);

        var newListing = new HereticStoreListingControl(listing, listingInStock, hasBalance, texture, extraText);
        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnListingButtonPressed?.Invoke(args, listing);

        StoreListingsContainer.AddChild(newListing);
    }

    /// <summary>
    /// Uses the discount text to display the required power for a particular listing.
    /// </summary>
    private string? GetExtraText(ListingDataWithCostModifiers listing)
    {
        if (listing.ProductHereticKnowledge != null)
        {
            //go on a long, arduous journey to get the stage of the knowledge
            var knowledgeID = listing.ProductHereticKnowledge;
            var knowledgeProto = _prototypeManager.Index<HereticKnowledgePrototype>(knowledgeID);
            var requiredPower = knowledgeProto.RequiredPower;

            return Loc.GetString("store-ui-heretic-level-display", ("power", requiredPower));
        }

        return null;
    }

    /// <summary>
    /// Get the price of a listing, as a string.
    /// </summary>
    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
        {
            text = Loc.GetString("store-currency-free");
            return text.TrimEnd();
        }

        foreach (var (type, amount) in listing.Cost)
        {
            var currency = _prototypeManager.Index(type);

            text += Loc.GetString(
                "store-ui-price-display",
                ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
            );
        }

        return text.TrimEnd();
    }

    /// <summary>
    /// Clear listings from the listing container.
    /// </summary>
    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
    }

    /// <summary>
    /// Add buttons to the category container.
    /// </summary>
    public void PopulateStoreCategoryButtons(HashSet<ListingDataWithCostModifiers> listings)
    {
        var allCategories = new List<StoreCategoryPrototype>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                var proto = _prototypeManager.Index(cat);
                if (!allCategories.Contains(proto))
                    allCategories.Add(proto);
            }
        }

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var catButton = new StoreCategoryButton
            {
                Text = Loc.GetString(proto.Name),
                Id = proto.ID,
                Pressed = proto.ID == CurrentCategory,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
            CategoryListContainer.AddChild(catButton);
        }
    }

    /// <summary>
    /// Close the window.
    /// </summary>
    public override void Close()
    {
        base.Close();
    }

    /// <summary>
    /// Store category button, with an ID.
    /// </summary>
    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }
}
