using Content.Shared._Starlight.CollectiveMind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterMindsControl : BoxContainer
{
    public CharacterMindsControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMinds(Dictionary<CollectiveMindPrototype, CollectiveMindMemberData> minds)
    {
        var mindDescriptionMessage = new FormattedMessage();
        mindDescriptionMessage.AddText(Loc.GetString("collective-mind-list-header"));
        foreach (var mindPrototype in minds)
        {
            mindDescriptionMessage.AddText("\n");
            mindDescriptionMessage.PushColor(mindPrototype.Key.Color);
            mindDescriptionMessage.AddText(Loc.GetString(
                "collective-mind-item",
                ("collective", mindPrototype.Key.LocalizedName),
                ("shortcut", $"+{mindPrototype.Key.KeyCode}")
            ));
            mindDescriptionMessage.AddText(Loc.GetString(
                "collective-mind-list-membership",
                ("id", mindPrototype.Value.MindId)
            ));
            mindDescriptionMessage.Pop();
        }

        Description.SetMessage(mindDescriptionMessage);
    }
}
