using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Impstation.Mime;
using Robust.Client.GameObjects;

namespace Content.Client._Impstation.Mime;

/// <summary>
/// Control for an individual mime gear.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MimeGearMenuSet : Control
{
    public MimeGearMenuSet(MimeGearMenuSetInfo set, SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);

        Icon.Texture = spriteSystem.Frame0(set.Sprite);
        SetName.Text = Loc.GetString(set.Name);
        SetDescription.Text = Loc.GetString(set.Description);
        SetButton.Text = Loc.GetString(set.Selected ? "thief-backpack-button-deselect" : "thief-backpack-button-select");
        SetButton.ModulateSelfOverride = set.Selected ? new Color(40, 84, 35) : new Color(68, 75, 103);
    }
}
