- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours, imp
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours, imp
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs, imp
    - !type:DepartmentTimeRequirement #imp
      department: Cargo
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement #imp
      department: Science
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 # 10 hours, imp
  weight: 20
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain #imp
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  #imp edit start
  - Courier
  - Logistics
  - Clown
  - Librarian
  - Mime
  - Musician
  - Reporter
  #imp edit end
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoPGear
  equipment:
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    belt: ClothingBeltPaperworkFilled # imp edit
  storage:
    back:
    - Flash
