using System.Text;
using Content.Client.Message;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Client.Xenoarchaeology.Artifact;
using Content.Client.Xenoarchaeology.Equipment;
using Content.Shared.Xenoarchaeology.Artifact.Components;
using Content.Shared.Xenoarchaeology.Equipment.Components;
using Content.Client.Power.Components; //IMP
using Content.Client.Power.EntitySystems; //IMP
using Content.Shared.Research.Components; //IMP
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Xenoarchaeology.Ui;

[GenerateTypedNameReferences]
public sealed partial class AnalysisConsoleMenu : FancyWindow
{
    private static readonly TimeSpan ExtractInfoDisplayForDuration = TimeSpan.FromSeconds(3);

    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly ArtifactAnalyzerSystem _artifactAnalyzer;
    private readonly XenoArtifactSystem _xenoArtifact;
    private readonly AdvancedNodeScannerSystem _advancedNodeScannerSystem; //imp: advanced node scanner system
    private readonly AudioSystem _audio;
    private readonly MetaDataSystem _meta = default!;

    private Entity<AnalysisConsoleComponent> _owner;
    private Entity<XenoArtifactNodeComponent>? _currentNode;

    private TimeSpan? _hideExtractInfoIn;
    private int _extractionSum;

    private Entity<AdvancedNodeScannerComponent> _advancedNodeScanner; //imp: advanced node scanner
    private TimeSpan? _unlockEndTime; //imp: advanced node scanner (reticulated only) display remaining unlock session time

    public event Action? OnServerSelectionButtonPressed;
    public event Action? OnExtractButtonPressed;

    // imp edit start, thusd buttons
    public event Action? OnShallowBiasButtonPressed;
    public event Action? OnDeepRandomBiasButtonPressed;
    public event Action? OnDeepLeftBiasButtonPressed;
    public event Action? OnDeepRightBiasButtonPressed;
    // imp edit end

    public AnalysisConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _xenoArtifact = _ent.System<XenoArtifactSystem>();
        _artifactAnalyzer = _ent.System<ArtifactAnalyzerSystem>();
        _advancedNodeScannerSystem = _ent.System<AdvancedNodeScannerSystem>(); //imp: advanced node scanner system
        _audio = _ent.System<AudioSystem>();
        _meta = _ent.System<MetaDataSystem>();

        if (BackPanel.PanelOverride is StyleBoxTexture tex)
            tex.Texture = _resCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");

        GraphControl.OnNodeSelected += node =>
        {
            _currentNode = node;
            SetSelectedNode(node);
        };

        ServerButton.OnPressed += _ =>
        {
            OnServerSelectionButtonPressed?.Invoke();
        };

        ExtractButton.OnPressed += StartExtract;

        // imp edit start
        ShallowBiasButton.OnPressed += _ =>
        {
            OnShallowBiasButtonPressed?.Invoke();
            _owner.Comp.BiasDirection = BiasDirection.Shallow;
            ShallowBiasButton.Pressed = true;
            DeepRandomBiasButton.Pressed = false;
            DeepLeftBiasButton.Pressed = false;
            DeepRightBiasButton.Pressed = false;
        };
        DeepRandomBiasButton.OnPressed += _ =>
        {
            OnDeepRandomBiasButtonPressed?.Invoke();
            _owner.Comp.BiasDirection = BiasDirection.DeepRandom;
            ShallowBiasButton.Pressed = false;
            DeepRandomBiasButton.Pressed = true;
            DeepLeftBiasButton.Pressed = false;
            DeepRightBiasButton.Pressed = false;
        };
        DeepLeftBiasButton.OnPressed += _ =>
        {
            OnDeepLeftBiasButtonPressed?.Invoke();
            _owner.Comp.BiasDirection = BiasDirection.DeepLeft;
            ShallowBiasButton.Pressed = false;
            DeepRandomBiasButton.Pressed = false;
            DeepLeftBiasButton.Pressed = true;
            DeepRightBiasButton.Pressed = false;
        };
        DeepRightBiasButton.OnPressed += _ =>
        {
            OnDeepRightBiasButtonPressed?.Invoke();
            _owner.Comp.BiasDirection = BiasDirection.DeepRight;
            ShallowBiasButton.Pressed = false;
            DeepRandomBiasButton.Pressed = false;
            DeepLeftBiasButton.Pressed = false;
            DeepRightBiasButton.Pressed = true;
        };
        // imp edit end
    }

    /// <summary>
    /// Set entity that corresponds analysis console, for which window is opened.
    /// Closes window if <see cref="AnalysisConsoleComponent"/> is not present on entity.
    /// </summary>
    public void SetOwner(EntityUid owner)
    {
        if (!_ent.TryGetComponent<AnalysisConsoleComponent>(owner, out var comp))
        {
            Close();
            return;
        }

        _owner = (owner, comp);
        Update(_owner);
    }

    private void StartExtract(BaseButton.ButtonEventArgs obj)
    {
        if (!_artifactAnalyzer.TryGetArtifactFromConsole(_owner, out var artifact))
            return;

        ExtractContainer.Visible = true;
        NodeViewContainer.Visible = false;

        _extractionSum = 0;
        var extractionMessage = new FormattedMessage();

        //IMP begin: Don't allow extract if research server is unpowered.
        if (!_ent.TryGetComponent<ResearchClientComponent>(_owner.Owner, out var researchClient))
            return; //Something went very wrong - Analysis console should ALWAYS have research client component

        if (researchClient.Server is not { } researchServer || !_ent.System<PowerReceiverSystem>().IsPowered(researchServer))
        {
            extractionMessage.AddMarkupOrThrow(Loc.GetString("analyzer-artifact-extract-failed-popup"));
            ExtractionResearchLabel.SetMessage(extractionMessage);
            _audio.PlayGlobal(_owner.Comp.ExtractionFailedSound, _owner, AudioParams.Default.WithVolume(0.7f));
            _hideExtractInfoIn = _timing.CurTime + ExtractInfoDisplayForDuration;
            return;
        }
        //IMP end

        var nodes = _xenoArtifact.GetAllNodes(artifact.Value);

        var count = 0;
        foreach (var node in nodes)
        {
            var pointValue = _xenoArtifact.GetResearchValue(node);
            if (pointValue <= 0)
                continue;

            count++;

            var nodeId = _xenoArtifact.GetNodeId(node);

            var text = Loc.GetString("analysis-console-extract-value", ("id", nodeId), ("value", pointValue));
            extractionMessage.AddMarkupOrThrow(text);
            extractionMessage.PushNewline();
            _extractionSum += pointValue; // imp fix, they forgot to do this
        }

        if (count == 0)
            extractionMessage.AddMarkupOrThrow(Loc.GetString("analysis-console-extract-none"));
        else if (artifact.Value.Comp.AdvancedNodeScanner is { } ansEntity && // imp edit start: advanced node scanner point bonus
            _ent.TryGetComponent<AdvancedNodeScannerComponent>(ansEntity, out var advancedNodeScanner)
            && (Math.Abs(advancedNodeScanner.PointMultiplier - 1) > 0.001 ))
        {
            var text = Loc.GetString("analysis-console-advanced-node-scanner-multiplier-bonus",
                ("multiplier", Math.Round(advancedNodeScanner.PointMultiplier, 3)),
                    ("bonus", Math.Round(_extractionSum * advancedNodeScanner.PointMultiplier - _extractionSum)));
            extractionMessage.AddMarkupOrThrow(text);
            _extractionSum = (int)Math.Round(_extractionSum * advancedNodeScanner.PointMultiplier);
        }
        // imp edit end

        _hideExtractInfoIn = _timing.CurTime + ExtractInfoDisplayForDuration;

        ExtractionResearchLabel.SetMessage(extractionMessage);
        ExtractionSumLabel.SetMarkup(Loc.GetString("analysis-console-extract-sum", ("value", _extractionSum)));

        _audio.PlayGlobal(_owner.Comp.ScanFinishedSound, _owner, AudioParams.Default.WithVolume(0.5f)); //#IMP 1f -> 0.5f
        OnExtractButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // imp edit: display remaining unlock time for reticulated artifacts if advanced node scanner is present
        _artifactAnalyzer.TryGetArtifactFromConsole(_owner, out var arti);

        if (arti is not null && arti.Value.Comp.AdvancedNodeScanner is not null)
        {
            Title = Loc.GetString("analysis-console-menu-title-with-advanced-node-scanner");
            if (!arti.Value.Comp.Natural)
            {
                // Minimise TryComp calls: save component
                if (arti.Value.Comp.AdvancedNodeScanner.Value != _advancedNodeScanner.Owner)
                {
                    if (_advancedNodeScannerSystem.TryGetAdvancedNodeScanner(_owner, out var advancedNodeScanner))
                        _advancedNodeScanner = advancedNodeScanner.Value;
                }

                if (_advancedNodeScannerSystem.GetCurrentUnlockSession(arti.Value, _advancedNodeScanner) is
                        { } unlockSession && unlockSession.EndTime is { } endTime)
                {
                    var remainingTime = (endTime - _timing.CurTime).TotalSeconds;
                    if (remainingTime <= 0f)
                        UnlockingTimeLabel.Visible = false;
                    else
                    {
                        UnlockingTimeLabel.Visible = true;
                        UnlockingTimeLabel.Text = Loc.GetString("analysis-console-unlock-time-text",
                            ("seconds", Math.Round(remainingTime, 1)));
                    }
                }
                else
                    UnlockingTimeLabel.Visible = false;
            }
            else
                UnlockingTimeLabel.Visible = false;
        }
        else
            Title = Loc.GetString("analysis-console-menu-title");
        // imp edit end

        if (_hideExtractInfoIn == null || _timing.CurTime + _meta.GetPauseTime(_owner) < _hideExtractInfoIn)
            return;

        ExtractContainer.Visible = false;
        NodeViewContainer.Visible = true;
        _hideExtractInfoIn = null;
    }

    public void Update(Entity<AnalysisConsoleComponent> ent)
    {
        _artifactAnalyzer.TryGetArtifactFromConsole(ent, out var arti);
        ArtifactView.SetEntity(arti);
        GraphControl.SetArtifact(arti);

        ExtractButton.Disabled = arti == null;

        if (arti == null)
            NoneSelectedLabel.Visible = false;

        // imp edit start, don't show the bias stuff if it doesn't need it
        if (arti is { Comp.Natural: true })
        {
            BiasBox.Visible = true;
            BiasDivider.Visible = true;
            if (arti.Value.Comp.AdvancedNodeScanner is not null)
            {
                DeepRandomBiasButton.Text = Loc.GetString("analysis-console-bias-deep-random");
                DeepLeftBiasButton.Visible = true;
                DeepRightBiasButton.Visible = true;
                BiasInternalDivider.Visible = true;
                BiasDeepInternalDivider.Visible = true;
            }
            else
            {
                DeepRandomBiasButton.Text = Loc.GetString("analysis-console-bias-deep");
                DeepLeftBiasButton.Visible = false;
                DeepRightBiasButton.Visible = false;
                BiasDeepInternalDivider.Visible = false;
            }
        }
        else
        {
            BiasBox.Visible = false;
            BiasDivider.Visible = false;
        }

        if (arti is { Comp.Natural: true })
        {
            _unlockEndTime = null;
            ShallowBiasButton.Pressed = false;
            DeepRandomBiasButton.Pressed = false;
            DeepLeftBiasButton.Pressed = false;
            DeepRightBiasButton.Pressed = false;
            if (ent.Comp.BiasDirection == BiasDirection.DeepLeft)
            {
                if (arti.Value.Comp.AdvancedNodeScanner is not null)
                {
                    DeepLeftBiasButton.Pressed = true;
                }
                else
                {
                    OnDeepRandomBiasButtonPressed?.Invoke();
                    ent.Comp.BiasDirection = BiasDirection.DeepRandom;
                    DeepRandomBiasButton.Pressed = true;
                }
            }
            else if (ent.Comp.BiasDirection == BiasDirection.DeepRight)
            {
                if (arti.Value.Comp.AdvancedNodeScanner is not null)
                {
                    DeepRightBiasButton.Pressed = true;
                }
                else
                {
                    OnDeepRandomBiasButtonPressed?.Invoke();
                    ent.Comp.BiasDirection = BiasDirection.DeepRandom;
                    DeepRandomBiasButton.Pressed = true;
                }
            }
            else if (ent.Comp.BiasDirection == BiasDirection.DeepRandom)
            {
                DeepRandomBiasButton.Pressed = true;

            }
            else if (ent.Comp.BiasDirection == BiasDirection.Shallow)
            {
                ShallowBiasButton.Pressed = true;
            }
        }
        // imp edit end

        NoArtiLabel.Visible = true;
        if (!_artifactAnalyzer.TryGetAnalyzer(ent, out _))
            NoArtiLabel.Text = Loc.GetString("analysis-console-info-no-scanner");
        else if (arti == null)
            NoArtiLabel.Text = Loc.GetString("analysis-console-info-no-artifact");
        else
            NoArtiLabel.Visible = false;

        if (_currentNode == null
            || arti == null
            || !_xenoArtifact.TryGetIndex((arti.Value, arti.Value), _currentNode.Value, out _))
        {
            SetSelectedNode(null);
        }
    }

    public void SetSelectedNode(Entity<XenoArtifactNodeComponent>? node)
    {
        InfoContainer.Visible = node != null;
        if (!_artifactAnalyzer.TryGetArtifactFromConsole(_owner, out var artifact))
            return;

        NoneSelectedLabel.Visible = node == null;

        if (node == null)
            return;

        var nodeId = _xenoArtifact.GetNodeId(node.Value);
        IDValueLabel.SetMarkup(Loc.GetString("analysis-console-info-id-value", ("id", nodeId)));

        // If active, state is 2. else, it is 0 or 1 based on whether it is unlocked, or not.
        int lockedState;
        if (_xenoArtifact.IsNodeActive(artifact.Value, node.Value))
            lockedState = 2;
        else
            lockedState = node.Value.Comp.Locked ? 0 : 1;

        LockedValueLabel.SetMarkup(Loc.GetString("analysis-console-info-locked-value", ("state", lockedState)));

        // imp edit start, if it's active and locked it's 3. hope this helps
        if (artifact.Value.Comp.Natural)
        {
            var currentState = _xenoArtifact.IsNodeActive(artifact.Value, node.Value) ? 1 : 0;
            CurrentValueLabel.SetMarkup(Loc.GetString("analysis-console-info-natural-current-value", ("state", currentState)));

            lockedState = node.Value.Comp.Locked ? 0 : 1;
            LockedLabel.SetMarkup(Loc.GetString("analysis-console-info-natural-locked"));
            LockedValueLabel.SetMarkup(Loc.GetString("analysis-console-info-natural-locked-value", ("state", lockedState)));
        }
        else
        {
            CurrentLabel.Visible = false;
            CurrentValueLabel.Visible = false;
        }
        // imp edit end

        var percent = (float) node.Value.Comp.Durability / node.Value.Comp.MaxDurability;
        var color = percent switch
        {
            >= 0.75f => Color.Lime,
            >= 0.50f => Color.Yellow,
            _ => Color.Red
        };
        DurabilityValueLabel.SetMarkup(Loc.GetString("analysis-console-info-durability-value",
            ("color", color),
            ("current", node.Value.Comp.Durability),
            ("max", node.Value.Comp.MaxDurability)));

        // imp edit start, if the artifact doesn't activate on interaction then durability isn't used. Don't show it
        if (!artifact.Value.Comp.ActivateOnInteraction)
        {
            DurabilityValueLabel.Visible = false;
            DurabilityLabel.Visible = false;
        }
        // imp edit end

        var hasInfo = _xenoArtifact.HasUnlockedPredecessor(artifact.Value, node.Value);

        // imp edit start, natural artifacts' nodes should only show their information if they're unlocked or active
        if (artifact.Value.Comp.Natural)
        {
            hasInfo = !node.Value.Comp.Locked || _xenoArtifact.IsNodeActive(artifact.Value, node.Value);

        }
        // imp edit end

        EffectValueLabel.SetMarkup(Loc.GetString("analysis-console-info-effect-value",
            ("state", hasInfo),
            ("info", _ent.GetComponentOrNull<MetaDataComponent>(node.Value)?.EntityDescription ?? string.Empty)));

        var predecessorNodes = _xenoArtifact.GetPredecessorNodes(artifact.Value.Owner, node.Value);
        if (!hasInfo)
        {
            TriggerValueLabel.SetMarkup(Loc.GetString("analysis-console-info-effect-value", ("state", false)));
        }
        else
        {
            var triggerStr = new StringBuilder();
            triggerStr.Append("- ");
            triggerStr.Append(Loc.GetString(node.Value.Comp.TriggerTip!));

            // imp edit start

            // foreach (var predecessor in predecessorNodes)
            // {
            //     triggerStr.AppendLine();
            //     triggerStr.Append("- ");
            //     triggerStr.Append(Loc.GetString(predecessor.Comp.TriggerTip!));
            // }

            if (artifact.Value.Comp.RequirePredecessorTriggers)
            {
                foreach (var predecessor in predecessorNodes)
                {
                    triggerStr.AppendLine();
                    triggerStr.Append("- ");
                    triggerStr.Append(Loc.GetString(predecessor.Comp.TriggerTip!));
                }
            }
            // imp edit end

            TriggerValueLabel.SetMarkup(Loc.GetString("analysis-console-info-triggered-value", ("triggers", triggerStr.ToString())));
        }

        ClassValueLabel.SetMarkup(Loc.GetString("analysis-console-info-class-value",
            ("class", Loc.GetString($"artifact-node-class-{Math.Min(6, predecessorNodes.Count + 1)}"))));
    }
}

