- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs, imp
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs, imp
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  extendedAccess:
  - Courier # Imp
  - Logistics #Imp

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
