- type: startingGear
  id: MobCargorillaGear
  equipment:
    ears: ClothingHeadsetCargo
    id: CargorillaIDCard

- type: startingGear
  id: GoblinRobeOSP
  equipment:
    outerClothing: ClothingOuterCoatRobesGoblin
    belt: ClothingBeltUtilityGoblinRandomFill

- type: startingGear
  id: GoblinOSPEVA
  equipment:
    outerClothing: ClothingOuterGoblinEVASuit
    belt: ClothingBeltUtilityGoblinRandomFill
    back: ClothingBackpackSatchelLeather
    suitstorage: OxygenTankFilled
  storage:
    back:
    - ClothingOuterCoatRobesGoblin

- type: startingGear
  id: GoblinKnightArmor
  equipment:
    neck: ClothingNeckGenderfluidPin
    outerClothing: ClothingOuterGoblinKnightArmor
    back: ClothingBackpackSatchelLeather
  inhand:
    - GoblinClaymore
    - WoodenBuckler

- type: startingGear
  id: DinoCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitTacticool
    outerClothing: ClothingOuterHardsuitDinoUnremoveable
    ears: ClothingHeadsetCommand
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack

- type: startingGear
  id: PositivityForceGear
  equipment:
    jumpsuit: ClothingUniformPositivityForce
    ears: ClothingHeadsetCommand
    eyes: ClothingEyesHudBeer
    head: ClothingHeadHatPositivityForcesoft
    shoes: ClothingShoesColorWhite
    back: ClothingBackpackSatchel
    neck: ClothingNeckPositivityForceMedal
    pocket1: ClothingNeckFuckhubMedal
    pocket2: DrinkSpaceLube
    id: ERTSecurityPDA

