book-text-ratkings = Rattus Sapiens - the species commonly referred to as “Rat King” - is notorious for many things. Its smell, its danger, its pervasiveness throughout nearly every sector in the modern universe. However, in this essay, I’d like to address one of its less-discussed aspects: its biology. The designation “Rattus Sapiens” is one that was given to it purely because of its physical appearance. This is not to say it does not fit - it is ratlike and sapient - but the difficulty of capturing a live specimen has made research into the Rat Kings near-impossible.

        That is, until recently. My sponsors at Nanotrasen were able to provide me with the first-ever known Rat King specimen to be contained alive. With their funding, I was able to construct a small space platform laboratory specifically built to contain and study the specimen. Sadly, my sponsors have requested I keep the nature of the containment procedure a trade secret.

        I would like to start with what I believe is my most interesting discovery: Rat Kings seem to have no common ancestors with the rats they are named after, despite their appearance. Rather, their skeletal and brain structure imply that they are most closely related to earth’s hominidae family. This, along with the first-ever records of Rat King sightings being located in systems nearby earth, leads me to believe they originate on Earth.

        Perhaps just as interesting is their relation to the “Rat Servants”. The Servants have no genealogical relation to the Kings. Rather, their genome matches very closely to Earth’s Rattus Norvegicus, or Brown Rat. This further lends credence to my theory that these creatures originated on Earth.

        It’s well known that Kings are able to produce Servants seemingly from thin air - however, my studies have shown that the King is not producing them directly. A Rat King has several Servants living in its fur at any given time. These servants are different from the ones normally seen following a King - they do not leave the fur, and seem to feed off of food scraps that the King leaves from its meals. For simplicity’s sake, I will refer to these non-active Servants as “Queens”.

        These Queens are the source of the Servants the King “produces”. The Servants seem to have a kind of social structure similar to that of Earth bees; The Queens are like queen bees, the attacker Servants are like worker drones, and the King acts as a mobile, intelligent hive. This mutual symbiosis is likely the reason the two species became so similar in appearance. Servants would be more likely to take orders from something they believe is one of them, so Rat Kings evolved to look rat-like.

        I would like to close out this short paper with a bit of conjecture. Based on what I have learned, I believe it likely that Rat Kings are human in origin. Their hominid genealogy, capability of speech, symbiosis with what seems to be a relative of Earth rats, and remarkable intelligence make this hard for me to ignore.

        If Rat Kings are truly mutant humans, as I suspect, then perhaps their origin lies within the sewers of earth cities. Perhaps they are the result of radioactive pollution or early experiments into gene editing. I would once again like to emphasize that this is pure conjecture - more research would be required for me to confidently propose such an outlandish concept.

        I would once again like to thank my sponsors at Nanotrasen for allowing me this research opportunity. They seem to share my hope that, one day, the Rat Kings may be able to work hand-in-hand alongside the rest of the universe.
