- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs, imp
    - !type:RoleTimeRequirement # imp
      role: JobSecurityOfficer
      time: 7200 #2 hrs
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hd
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
#    id: LawyerPDA # imp, PDAs moved to loadout
    ears: ClothingHeadsetLawyer # imp edit
#  inhand: # imp, briefcases moved to loadout
#    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
