using System.Linq;
using System.Text;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Heretic.Prototypes;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Impstation.Uplink;

/// <summary>
/// Control for the uplink.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class UplinkMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private UplinkWithdrawWindow? _withdrawWindow;

    public event EventHandler<string>? SearchTextUpdated;
    public event Action<BaseButton.ButtonEventArgs, ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;
    public event Action<BaseButton.ButtonEventArgs>? OnRefundAttempt;

    public Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> Balance = new();
    public string CurrentCategory = string.Empty;

    private List<ListingDataWithCostModifiers> _cachedListings = new();

    public UplinkMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        RefundButton.OnButtonDown += OnRefundButtonDown;
        SearchBar.OnTextChanged += _ => SearchTextUpdated?.Invoke(this, SearchBar.Text);
    }

    /// <summary>
    /// Update the current balance, enable the withdraw button if applicable.
    /// </summary>
    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        Balance = balance;

        var currency = balance.ToDictionary(type =>
            (type.Key, type.Value), type => _prototypeManager.Index(type.Key));

        var balanceStr = string.Empty;
        foreach (var ((_, amount), proto) in currency)
        {
            balanceStr += Loc.GetString("store-ui-price-display", ("amount", amount),
                ("currency", Loc.GetString(proto.DisplayName, ("amount", 1)))) + "\n";
        }

        RichTextLabelExt.SetMarkup(BalanceInfo, balanceStr.TrimEnd());

        var disabled = true;
        foreach (var type in currency)
        {
            if (type.Value.CanWithdraw && type.Value.Cash != null && type.Key.Item2 > 0)
            {
                disabled = false;
                break;
            }
        }

        WithdrawButton.Disabled = disabled;
    }

    /// <summary>
    /// Update every listing.
    /// </summary>
    public void UpdateListing(List<ListingDataWithCostModifiers> listings)
    {
        _cachedListings = listings;

        UpdateListing();
    }

    /// <summary>
    /// Get every possible listing and add them to the listing container.
    /// </summary>
    public void UpdateListing()
    {
        var sorted = _cachedListings.OrderBy(l => l.Priority)
                                    .ThenBy(l => l.Cost.Values.Sum());

        // should probably chunk these out instead. to-do if this clogs the internet tubes.
        // maybe read clients prototypes instead?
        ClearListings();
        foreach (var item in sorted)
        {
            AddListingGui(item);
        }
    }

    /// <summary>
    /// Open the withdraw window.
    /// </summary>
    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        // check if window is already open
        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        // open a new one
        _withdrawWindow = new UplinkWithdrawWindow();
        _withdrawWindow.OpenCentered();

        _withdrawWindow.CreateCurrencyButtons(Balance);
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    /// <summary>
    /// Send the attempt refund action.
    /// </summary>
    private void OnRefundButtonDown(BaseButton.ButtonEventArgs args)
    {
        OnRefundAttempt?.Invoke(args);
    }

    /// <summary>
    /// Get the specific listing's data and make a new listing control for it, then add it to the listing container.
    /// </summary>
    private void AddListingGui(ListingDataWithCostModifiers listing)
    {
        if (!listing.Categories.Contains(CurrentCategory))
            return;

        var hasBalance = listing.CanBuyWith(Balance);

        var spriteSys = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();

        Texture? texture = null;
        if (listing.Icon != null)
            texture = spriteSys.Frame0(listing.Icon);

        if (listing.ProductEntity != null)
        {
            if (texture == null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;
        }
        else if (listing.ProductAction != null)
        {
            var actionId = _entityManager.Spawn(listing.ProductAction);
            if (_entityManager.System<ActionsSystem>().GetAction(actionId)?.Comp?.Icon is {} icon)
                texture = spriteSys.Frame0(icon);
        }
        //imp edit
        //i hate UI code i hate it with my life
        //hopefully this is useful for other people messing with stores
        string? extraText = GetExtraText(listing);

        var listingInStock = GetListingPriceString(listing);
        var discount = GetDiscountString(listing);

        var newListing = new UplinkMarketListing(listing, listingInStock, discount, hasBalance, texture, extraText); // imp extratext
        newListing.StoreItemBuyButton.OnButtonDown += args
            => OnListingButtonPressed?.Invoke(args, listing);

        StoreListingsContainer.AddChild(newListing);
    }

    //imp edit
    //this will replace the text area usually reserved for discount info.
    //this will ALWAYS show up, as opposed to discounts, which are hidden on unavailable items
    private string? GetExtraText(ListingDataWithCostModifiers listing)
    {
        if (listing.ProductHereticKnowledge != null)
        {
            //go on a long, arduous journey to get the stage of the knowledge
            var knowledgeID = listing.ProductHereticKnowledge;
            var knowledgeProto = _prototypeManager.Index<HereticKnowledgePrototype>(knowledgeID);
            var requiredPower = knowledgeProto.RequiredPower;

            return Loc.GetString("store-ui-heretic-level-display", ("power", requiredPower));
        }

        return null;
    }
    // imp edit end

    /// <summary>
    /// Get the price of the listing and get the string for it.
    /// </summary>
    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        var text = string.Empty;

        if (listing.Cost.Count < 1)
            text = Loc.GetString("store-currency-free");
        else
        {
            foreach (var (type, amount) in listing.Cost)
            {
                var currency = _prototypeManager.Index(type);

                text += Loc.GetString(
                    "store-ui-price-display",
                    ("amount", amount),
                    ("currency", Loc.GetString(currency.DisplayName, ("amount", amount)))
                );
            }
        }

        return text.TrimEnd();
    }

    /// <summary>
    /// Make a string to represent how much the listing has been discounted by.
    /// </summary>
    private string GetDiscountString(ListingDataWithCostModifiers listingDataWithCostModifiers)
    {
        string discountMessage;
        var sb = new StringBuilder(); // imp moved this up


        if (!listingDataWithCostModifiers.IsCostModified)
        {
            return string.Empty;
        }

        var relativeModifiersSummary = listingDataWithCostModifiers.GetModifiersSummaryRelative();
        if (relativeModifiersSummary.Count > 1)
        {
            // var sb = new StringBuilder(); // imp moved it up
            sb.Append('(');
            foreach (var (currency, amount) in relativeModifiersSummary)
            {
                var currencyPrototype = _prototypeManager.Index(currency);
                if (sb.Length != 0)
                {
                    sb.Append(", ");
                }
                var currentDiscountMessage = Loc.GetString(
                    "store-ui-discount-display-with-currency",
                    ("amount", amount.ToString("P0")),
                    ("currency", Loc.GetString(currencyPrototype.DisplayName))
                );
                sb.Append(currentDiscountMessage);
            }

            sb.Append(')');
            discountMessage = sb.ToString();
        }
        else
        {
            // if cost was modified - it should have diff relatively to original cost in 1 or more currency
            // ReSharper disable once GenericEnumeratorNotDisposed Dictionary enumerator doesn't require dispose
            var enumerator = relativeModifiersSummary.GetEnumerator();
            enumerator.MoveNext();
            var amount = enumerator.Current.Value;
            discountMessage = Loc.GetString(
                "store-ui-discount-display",
                ("amount", (amount.ToString("P0")))
            );
        }

        return discountMessage;
    }

    /// <summary>
    /// Clear every listing from the listing container.
    /// </summary>
    private void ClearListings()
    {
        StoreListingsContainer.Children.Clear();
    }

    /// <summary>
    /// Go over each listing available to the store and add a button to the category container representing every
    /// category included at least once.
    /// </summary>
    public void PopulateStoreCategoryButtons(HashSet<ListingDataWithCostModifiers> listings)
    {
        var allCategories = new List<StoreCategoryPrototype>();
        foreach (var listing in listings)
        {
            foreach (var cat in listing.Categories)
            {
                var proto = _prototypeManager.Index(cat);
                if (!allCategories.Contains(proto))
                    allCategories.Add(proto);
            }
        }

        allCategories = allCategories.OrderBy(c => c.Priority).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category.ID != CurrentCategory))
            CurrentCategory = string.Empty;

        if (CurrentCategory == string.Empty && allCategories.Count > 0)
            CurrentCategory = allCategories.First().ID;

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var catButton = new StoreCategoryButton
            {
                Text = Loc.GetString(proto.Name),
                Id = proto.ID,
                Pressed = proto.ID == CurrentCategory,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" },
                TextAlign = Label.AlignMode.Left,
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
            CategoryListContainer.AddChild(catButton);
        }
    }

    /// <summary>
    /// Close the window, and the withdraw window.
    /// </summary>
    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }

    /// <summary>
    /// Set the refund button's visibility to the supplied value.
    /// </summary>
    public void UpdateRefund(bool allowRefund)
    {
        RefundButton.Visible = allowRefund;
    }

    /// <summary>
    /// Button with an id, for category buttons.
    /// </summary>
    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }
}
