- type: gameMapPool
  id: DefaultMapPoolImp
  maps:
  # WIZDEN MAPS
  - AmberImp
  - BagelImp
  - BoxImp
  - Cluster
  - CogImp
  - CoreImp
  - ElkridgeImp
  - GateImp
  - MarathonImp
  - OasisImp
  - PackedImp
  - PlasmaImp
  - ReachImp
  - SalternImp
  - TrainImp
  - Xeno #aka exo
  # IMP MAPS:
  - Banana
  - Bedlam
  - Boat
  - Hummingbird
  - Lilboat
  - Luna
  - Pathway
  - Whisper
  # DELTAV MAPS:
  - Submarine
  # HARMONY MAPS:
  - Barratry
  - Eclipse
